config/routes.rb
Rails.application.routes.draw do
  get 'developer/show'
  get 'developer/index'
  devise_for :developers
  get 'tester/show'
  get 'tester/index'
  devise_for :testers
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'pages#home'
  get :test, to: 'pages#test'
  get :add_bug, to: 'pages#bug_form'
  post :add_bug, to: 'bugs#create'
  put "/update_status" => 'bugs#update_status'
  resources :bugs do
    collection do
      put ":id/update" => 'bugs#update', as: :update
    end
  end

   
  

  # Defines the root path route ("/")
  # root "articles#index"
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bug.rb
class Bug < ApplicationRecord
  enum status: {unsolved: 0, taken:1, solved: 2, closed: 3}
  belongs_to :tester
  belongs_to :developer, optional: true
  validates :tester_id, presence: true
end

app/models/developer.rb
class Developer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bugs
end

app/models/tester.rb
class Tester < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bugs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  
  def create
    @bug = current_tester.bugs.build(bug_params)
    if(@bug.save)
      flash[:succes] = "Bug added!"
    else 
      flash[:error] = "There was an error!"
    end
    redirect_to root_path
  end

  def edit
    @bug = Bug.find(params[:id])
  end

  def update
    @bug = Bug.find(params[:id])
    if @bug.update(bug_params)
      flash[:notice] = "Bug updated"
    else
      flash[:notice] = "Something went wrong"
    end
    redirect_to root_path
  end

  def update_status
    @bug = Bug.find(params[:bug][:id])
    if @bug.status == "unsolved"
      @bug.update(developer_id: current_developer.id)
    end
    if @bug.update(bug_params)
      flash[:notice] = "Bug updated"
    else
      flash[:notice] = "Something went wrong"
    end
    redirect_to root_path
  end

  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy
    flash[:success] = "Bug deleted"
    redirect_to root_url
  end

  private
    def bug_params
      params.require(:bug).permit(:id,:title, :status, :description,:developer_id)
    end

end

app/controllers/developer_controller.rb
class DeveloperController < ApplicationController
  def show
  end

  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if tester_signed_in?
      @bugs = current_tester.bugs.order(status: :asc, created_at: :desc)
    end
    if developer_signed_in?
      @bugs = Bug.all.order(status: :asc, created_at: :desc)
    end
  end

  def test
  end
  
  def bug_form
    @tester = current_tester
  end
end

app/controllers/tester_controller.rb
class TesterController < ApplicationController
  def show
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/developer_helper.rb
module DeveloperHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tester_helper.rb
module TesterHelper
end

app/views/bugs/_bug.html.haml
-# %div.box-border.h-64.w-64.text-white.border-4.rounded
-#   %p.text-center.text-lg.justify-self-center
-#     = bug.title
-#   %p  
-#     = bug.description
.items-center.rounded-lg.shadow.sm:flex.bg-gray-800.border-gray-700
  .p-5
    %h3.text-xl.font-bold.tracking-tight.text-white
      - if tester_signed_in?
        %a{:href => edit_bug_path(bug.id)}= bug.title
      - else 
        =bug.title
    - unless bug.developer_id.nil?
      %span.text-gray-400=bug.status.capitalize + " by " + Developer.find(bug.developer_id).name
    - else
      %span.text-gray-400=bug.status.capitalize
    %p.mt-3.mb-4.font-light.text-gray-400=bug.description

    - if developer_signed_in?
      = form_for(bug, url: update_status_path, html: { method: :put }) do |f|
        - stat = "Solved"
        - if bug.status == "unsolved"
          = f.hidden_field :status, as: :hidden, value: :taken
          - stat = "Take"
        - elsif bug.status == "taken"
          = f.hidden_field :status, as: :hidden, value: :solved
          - stat = "Mark as solved"
        = f.hidden_field :id, as: :hidden, value: bug.id
        - if bug.developer_id.nil? || bug.developer_id == current_developer.id
          .actions
            %button.btn.box-border.text-white.text-center.justify-center.box.bg-gray-600.hover:bg-gray-700.w-48.rounded.flex
              = f.submit stat, class: 'py-2.5', role: "button"  
        - else
          .actions
          %button.btn.box-border.text-white.text-center.justify-center.box.bg-gray-700.w-48.rounded.flex{disabled: "disabled"}
            = f.submit stat, class: 'py-2.5', role: "button", disabled: "disabled"
    - elsif tester_signed_in? && bug.status == "closed"
      .text-red-800 
        = link_to "delete", bug, method: :delete, data: { confirm: "You sure?" }
  

app/views/bugs/edit.html.haml
%section.bg-gray-900
  .flex.flex-col.items-center.justify-center.px-4.py-8.mx-auto.lg:py-0
    %h1.text-white.font-bold.text-4xl.mb-4.mt-10 Edit Bug
    .w-full.rounded-lg.shadow.border.md:mt-0.sm:max-w-md.xl:p-0.bg-gray-800.border-gray-700
      .p-6.space-y-4.md:space-y-6.sm:p-8 
        = form_for(@bug, url: update_bugs_path, html: { method: :put }) do |f|
          = render "devise/shared/error_messages", resource: f.object
          .field
            .block.mb-2.text-sm.font-medium.text-white
              = f.label :title
              = f.text_field :title, autofocus: true, required: true, class: "border sm:text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500"
          .field
            .block.mb-2.text-sm.font-medium.text-white
              = f.select :status, options_for_select(Bug.statuses.map{ |k, v|  [k.humanize.capitalize, k]})
          .field
            .block.mb-2.text-sm.font-medium.text-white
              = f.label :description
              = f.text_area :description,required: true, class: "border sm:text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500"
          .actions
            %button.btn.w-full.text-white.focus:ring-4.focus:outline-none.font-medium.rounded-lg.text-sm.px-5.text-center.bg-primary-600.hover:bg-primary-700.focus:ring-primary-800
              = f.submit "Update bug", class: 'py-2.5', role: "button"

app/views/developer/index.html.haml
%div
  %h1.font-bold.text-4xl Developer#index
  %p Find me in app/views/developer/index.html.erb

app/views/developer/show.html.haml
%div
  %h1.font-bold.text-4xl Developer#show
  %p Find me in app/views/developer/show.html.erb

app/views/layouts/_alert.html.haml
- if alert
  #alert-alert.flex.p-4.bg-red-100.border-t-4.border-red-500.dark:bg-red-200{:role => "alert"}
    %svg.flex-shrink-0.w-5.h-5.text-red-700{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
      %path{"clip-rule" => "evenodd", :d => "M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z", "fill-rule" => "evenodd"}
    .ml-3.text-sm.font-medium.text-red-700
      = alert
    %button.ml-auto.bg-red-100.dark:bg-red-200.text-red-500.rounded-lg.focus:ring-2.focus:ring-red-400.hover:bg-red-200.dark:hover:bg-red-300.inline-flex.h-8.w-8{"aria-label" => "Close", :class => "-mx-1.5 -my-1.5 p-1.5", "data-dismiss-target" => "#alert-alert", :type => "button"}
      %span.sr-only Dismiss
      %svg.w-5.h-5{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z", "fill-rule" => "evenodd"}

app/views/layouts/_footer.html.haml
%footer.shadow.bg-gray-900
  .w-full.max-w-screen-xl.mx-auto.p-4.md:py-8
    .sm:flex.sm:items-center.sm:justify-between
      %ul.flex.flex-wrap.items-center.mb-6.text-sm.font-medium.sm:mb-0.text-gray-400
        %li
          %a.mr-4.hover:underline.md:mr-6{:href => "#"} About
        %li
          %a.mr-4.hover:underline.md:mr-6{:href => "#"} Privacy Policy
        %li
          %a.mr-4.hover:underline.md:mr-6{:href => "#"} Licensing
        %li
          %a.hover:underline{:href => "#"} Contact
    %hr.my-6.sm:mx-auto.border-gray-700.lg:my-8/
    %span.block.text-sm.sm:text-center.text-gray-400
      © 2023
      = succeed "." do
        %a.hover:underline BugHunt™

app/views/layouts/_navbar.html.haml
%nav.bg-gray-900.border-gray-900.px-6.sm:px-4{:class => "py-2.5"}
  .container.flex.flex-wrap.justify-between.items-center.mx-auto
    %a.flex.items-center.lg:pl-0.pl-2{:href => root_path}
      %img.mr-3.h-14.md:h-9{:alt => "WebPets Logo", :src => image_path("logo.png")}/
      %span.self-center.text-2xl.font-semibold.whitespace-nowrap.text-white BugHunt
    %button.inline-flex.items-center.py-2.pl-2.ml-3.text-sm.text-black.rounded-lg.md:hidden{"aria-controls" => "navbar-default", "aria-expanded" => "false", "data-collapse-toggle" => "navbar-default", :type => "button"}
      %span.sr-only Open main menu
      %svg.w-12.h-12{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z", "fill-rule" => "evenodd"}
    #navbar-default.hidden.w-full.md:block.md:w-auto
      %ul.flex.flex-col.md:items-center.py-2.mt-4.rounded-lg.border.md:flex-row.md:space-x-8.md:mt-0.md:text-sm.md:font-medium.md:border-0.bg-gray-800.md:bg-gray-900.border-gray-700
        - if tester_signed_in?
          %li
            = link_to "Sign out", destroy_tester_session_url, method: :delete, class:"block py-2 pr-4 pl-3 rounded md:border-0 md:p-0 text-gray-400 hover:text-white hover:bg-gray-700 hover:text-white hover:bg-transparent"
          %li
            = link_to "Account", tester_show_path, class:"block py-2 pr-4 pl-3 rounded md:border-0 md:p-0 text-gray-400 hover:text-white hover:bg-gray-700 hover:text-white hover:bg-transparent"
        - elsif developer_signed_in?
          = link_to "Log out", destroy_developer_session_url, method: :delete, class:"block py-2 pr-4 pl-3 rounded md:border-0 md:p-0 text-gray-400 hover:text-white hover:bg-gray-700 hover:text-white hover:bg-transparent"
          = link_to "Account", developer_show_path, class:"block py-2 pr-4 pl-3 rounded md:border-0 md:p-0 text-gray-400 hover:text-white hover:bg-gray-700 hover:text-white hover:bg-transparent"
        - else
          %li
            = link_to "Sign in", new_tester_session_url, class:"block py-2 pr-4 pl-3 rounded md:border-0 md:p-0 text-gray-400 hover:text-white hover:bg-gray-700 hover:text-white hover:bg-transparent"

app/views/layouts/_notice.html.haml
- if notice
  #alert-notice.flex.p-4.bg-blue-100.border-t-4.border-blue-500.dark:bg-blue-200{:role => "alert"}
    %svg.flex-shrink-0.w-5.h-5.text-blue-700{:fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
      %path{"clip-rule" => "evenodd", :d => "M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z", "fill-rule" => "evenodd"}
    .ml-3.text-sm.font-medium.text-blue-700
      = notice
    %button.ml-auto.bg-blue-100.dark:bg-blue-200.text-blue-500.rounded-lg.focus:ring-2.focus:ring-blue-400.hover:bg-blue-200.dark:hover:bg-blue-300.inline-flex.h-8.w-8{"aria-label" => "Close", :class => "-mx-1.5 -my-1.5 p-1.5", "data-dismiss-target" => "#alert-notice", :type => "button"}
      %span.sr-only Dismiss
      %svg.w-5.h-5{"aria-hidden" => "true", :fill => "currentColor", :viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %path{"clip-rule" => "evenodd", :d => "M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z", "fill-rule" => "evenodd"}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BugHunt
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    
    =render 'layouts/navbar'
    = render 'layouts/notice'
    = render 'layouts/alert'
    = yield
    =render 'layouts/footer'

app/views/pages/bug_form.haml
%section.bg-gray-900
  .flex.flex-col.items-center.justify-center.px-4.py-8.mx-auto.lg:py-0
    %h1.text-white.font-bold.text-4xl.mb-4.mt-10 BugHunt``
    .w-full.rounded-lg.shadow.border.md:mt-0.sm:max-w-md.xl:p-0.bg-gray-800.border-gray-700
      .p-6.space-y-4.md:space-y-6.sm:p-8 
        = form_with(model: @tester.bugs.build) do |f|
          = render "devise/shared/error_messages", resource: f.object
          .field
            .block.mb-2.text-sm.font-medium.text-white
              = f.label :title
              = f.text_field :title, autofocus: true, required: true, class: "border sm:text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500"
          .field
            .block.mb-2.text-sm.font-medium.text-white
              = f.hidden_field :status, as: :hidden, value: :unsolved
          .field
            .block.mb-2.text-sm.font-medium.text-white
              = f.label :description
              = f.text_area :description,required: true, class: "border sm:text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500"
          .actions
            %button.btn.w-full.text-white.focus:ring-4.focus:outline-none.font-medium.rounded-lg.text-sm.px-5.text-center.bg-primary-600.hover:bg-primary-700.focus:ring-primary-800
              = f.submit "Add new bug", class: 'py-2.5', role: "button"

app/views/pages/home.html.haml
%div.bg-gray-900.flex.flex-col.items-center
  %h1.font-bold.text-4xl.text-center.text-white BugHunt
  %p.text-white.text-center.mb-5 Let's hunt them down!

  
  - if tester_signed_in?
    .grid.gap-8.px-4.py-6.lg:py-10.md:grid-cols-2
      = render @bugs
    
    .btn.box-border.text-white.text-center.justify-center.box.bg-gray-800.hover:bg-gray-700.w-48.rounded.flex
      = link_to "Add New Bug", add_bug_path, class: "py-2 px-11"
  - elsif developer_signed_in?
    .grid.gap-8.px-4.py-6.lg:py-10.md:grid-cols-2
      = render @bugs
  - else 
    .grid.justify-center  
      .grid.grid-flow.flex.gap-6.mb-4.sm:grid-cols-2.justify-center
        .btn.box-border.h-32.flex.w-32.items-center.text-center.border-4.bg-gradient-to-r.from-indigo-600.to-pink-500.hover:from-indigo-700.hover:to-pink-600.text-white.hover
          = link_to "Login as Tester", new_tester_session_url, class:"py-10 font-bold px-1"
        .btn.box-border.h-32.flex.w-32.items-center.text-center.border-4.bg-gradient-to-r.from-indigo-600.to-pink-500.hover:from-indigo-700.hover:to-pink-600.text-white.hover
          = link_to "Login as Developer", new_developer_session_url, class:"py-10 font-bold px-1"

    

app/views/pages/test.html.haml
%section.bg-gray-50.dark:bg-gray-900
  .flex.flex-col.items-center.justify-center.px-6.py-8.mx-auto.md:h-screen.lg:py-0
    %a.flex.items-center.mb-6.text-2xl.font-semibold.text-gray-900.dark:text-white{:href => "#"}
      %img.w-8.h-8.mr-2{:alt => "logo", :src => "https://flowbite.s3.amazonaws.com/blocks/marketing-ui/logo.svg"}/
      Flowbite
    .w-full.bg-white.rounded-lg.shadow.dark:border.md:mt-0.sm:max-w-md.xl:p-0.dark:bg-gray-800.dark:border-gray-700
      .p-6.space-y-4.md:space-y-6.sm:p-8
        %h1.text-xl.font-bold.leading-tight.tracking-tight.text-gray-900.md:text-2xl.dark:text-white
          Sign in to your account
        %form.space-y-4.md:space-y-6{:action => "#"}
          %div
            %label.block.mb-2.text-sm.font-medium.text-gray-900.dark:text-white{:for => "email"} Your email
            %input#email.bg-gray-50.border.border-gray-300.text-gray-900.sm:text-sm.rounded-lg.focus:ring-primary-600.focus:border-primary-600.block.w-full.dark:bg-gray-700.dark:border-gray-600.dark:placeholder-gray-400.dark:text-white.dark:focus:ring-blue-500.dark:focus:border-blue-500{:class => "p-2.5", :name => "email", :placeholder => "name@company.com", :required => "", :type => "email"}/
          %div
            %label.block.mb-2.text-sm.font-medium.text-gray-900.dark:text-white{:for => "password"} Password
            %input#password.bg-gray-50.border.border-gray-300.text-gray-900.sm:text-sm.rounded-lg.focus:ring-primary-600.focus:border-primary-600.block.w-full.dark:bg-gray-700.dark:border-gray-600.dark:placeholder-gray-400.dark:text-white.dark:focus:ring-blue-500.dark:focus:border-blue-500{:class => "p-2.5", :name => "password", :placeholder => "••••••••", :required => "", :type => "password"}/
          .flex.items-center.justify-between
            .flex.items-start
              .flex.items-center.h-5
                %input#remember.w-4.h-4.border.border-gray-300.rounded.bg-gray-50.focus:ring-3.focus:ring-primary-300.dark:bg-gray-700.dark:border-gray-600.dark:focus:ring-primary-600.dark:ring-offset-gray-800{"aria-describedby" => "remember", :required => "", :type => "checkbox"}/
              .ml-3.text-sm
                %label.text-gray-500.dark:text-gray-300{:for => "remember"} Remember me
            %a.text-sm.font-medium.text-primary-600.hover:underline.dark:text-primary-500{:href => "#"} Forgot password?
          %button.w-full.text-white.bg-primary-600.hover:bg-primary-700.focus:ring-4.focus:outline-none.focus:ring-primary-300.font-medium.rounded-lg.text-sm.px-5.text-center.dark:bg-primary-600.dark:hover:bg-primary-700.dark:focus:ring-primary-800{:class => "py-2.5", :type => "submit"} Sign in
          %p.text-sm.font-light.text-gray-500.dark:text-gray-400
            Don't have an account yet?
            %a.font-medium.text-primary-600.hover:underline.dark:text-primary-500{:href => "#"} Sign up

app/views/tester/index.html.haml
%div
  %h1.font-bold.text-4xl Tester#index
  %p Find me in app/views/tester/index.html.erb

app/views/tester/show.html.haml
%div
  %h1.font-bold.text-4xl Tester#show
  %p Find me in app/views/tester/show.html.erb